version: '2'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  api:
    container_name: backend_app
    build: .
    env_file: .env
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080
      - MINIO_ENDPOINT=minio:9000
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - postgres
      - minio

  minio:
    image: minio/minio
    restart: always
    env_file: .env
    ports:
      - "9000:9000"
    command: server /data
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: