version: '2'

services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/

  api:
    container_name: backend_app
    build: .
    env_file: .env
    restart: always
    ports:
      - "80:8080"
    depends_on:
      - postgres
    command: go run main.go


volumes:
  pgdata: